### ISSUE TITLE
add snap interface removable-media

### ISSUE THREAD

**Issue by nguypaul** [pkg-src/jdownloader2.snap#1]
Issue:
jdownloader2 is unable to set download folder to /media or /mnt locations. Please add the snap interface removable-media https://snapcraft.io/docs/removable-media-interface

Also have this interface auto connect.

I am using Ubuntu 20.04 and my secondary hdd, USB drives, and SD cards auto mount to /media.

**Comment by fnkr** [comment]
Hi,

I've added a plug for the interface and pushed a new build to the candidate channel. Please confirm that this works for you and I will push it to the stable channel afterwards.

```
snap refresh jdownloader2 --channel=latest/candidate
snap connect jdownloader2:removable-media
```

Regarding auto-connect: the interface is not auto-connect by default, which means the Snap Store team has to approve this first. I've filed an auto-connection request: https://forum.snapcraft.io/t/auto-connection-request-for-jdownloader2-removable-media/17851

**Comment by nguypaul** [comment]
Thank you very much. I have confirmed it is working now.
